/* Hello world against real musl libc: crt1 startup, stdio, the works.
 * Every translation unit that ends up in the binary — including the ~40
 * musl TUs printf pulls in — is compiled by the proven TCC, and the link
 * is proven too (see build.json, generated by prepare.sh). */
#include <stdio.h>

int main(void)
{
    printf("hello, musl %d\n", 42);
    return 0;
}
